### ISSUE TITLE
Webpages don't get updated automatically

### ISSUE THREAD

**Issue by damirka** [AleoHQ/welcome#100]
Looks like changes don't apply to the website on PR merge. Maybe we could set up some CI to do it? Or any other alternative such as a webhook? 

As an example of this behavior:
1. Merged PR: https://github.com/AleoHQ/welcome/pull/98/files
2. No information on this page: https://developer.aleo.org/developer/language/variables/

**Comment by aharshbe** [comment]
Closing this as we have an internal process for updating docs. Thank you for opening the issue @damirka.
