### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by rapiz1** [AleoHQ/welcome#108]
In pages like https://developer.aleo.org/advanced/posw/posw/, some latex code can be seen but not rendered, which is not easy to read. It will be useful if mathjax is loaded on the page.
![image](https://user-images.githubusercontent.com/20105061/150726509-b3c01819-3f1f-4901-8da5-291d091aba9c.png)

**Comment by aharshbe** [comment]
Closing since this has already been changed. Thanks for opening the issue @rapiz1.
