### ISSUE TITLE
`documentation/developer/language/11_console.md` is out of date

### ISSUE THREAD

**Issue by rapiz1** [AleoHQ/welcome#110]
https://github.com/AleoHQ/welcome/blob/34b6b79b1357e69eac2c5e05823a703d239073b4/documentation/developer/language/11_console.md?plain=1#L68

This is no longer true. Variable values are printed in the build stage now.

**Comment by aharshbe** [comment]
Closing since this is out of date and no longer relevant. Thank you @rapiz1 for opening!
