### ISSUE TITLE
Lengths of private keys, proving keys, and account view keys

### ISSUE THREAD

**Issue by acoglio** [AleoHQ/welcome#116]
The page https://developer.aleo.org/concepts/accounts says that:
- A private key consists of 58 characters, but the example consists of 56 characters.
- A proving key consists of 58 characters, but the example consists of 57 characters. 
- An account view key consists of 56 characters, but the example consists of 53 characters.

I'm not sure how to fix this, because I don't know enough of these formats yet to determined if the error is in the assertions or in the examples. That's why I'm opening an Issue instead of a PR.

**Comment by collinc97** [comment]
closed by 168
