### ISSUE TITLE
Accounts module is outdated, it have been replaced by `snarkos account new`

### ISSUE THREAD

**Issue by LouisWT** [AleoHQ/welcome#170]
Run `cargo run` in accounts dir, we got errors.
![image](https://user-images.githubusercontent.com/22902565/233895350-e0e8fddb-52e3-4a50-ac93-84a21b03a8b3.png)
Because project structure have changed a lot in 3 years.

**Comment by aharshbe** [comment]
[Created a PR](https://github.com/AleoHQ/welcome/pull/194) to delete this; thank you for opening the issue @LouisWT.
