### ISSUE TITLE
Does Aleo have any public RPC endpoint?

### ISSUE THREAD

**Issue by naddika** [AleoHQ/welcome#175]
Does Aleo have any public RPC endpoint?

**Comment by aharshbe** [comment]
Hey @naddika, currently, Aleo does not maintain a public RPC endpoint. We do have [a public API](https://apiv2.aleo.network/) you can query, though, depending on the functionality you want to implement. If you have further questions, feel free to send our Tech Ops team an email via techops@aleo.org.
