### ISSUE TITLE
Remove strings from Aleo instructions and Leo documentation

### ISSUE THREAD

**Issue by acoglio** [AleoHQ/welcome#183]
As these are currently not implemented, we should align the documentation to the implementation.

It seems best to do this after https://github.com/AleoHQ/welcome/pull/177 is merged, because the changes are not disjoint.

**Comment by moAlobaidi** [comment]
Hi @acoglio! Looking into this issue, but I can't find a mention of strings in the Aleo instructions or Leo documentation. Can you please send a link to what you're referring to?

**Comment by aharshbe** [comment]
Hey @moAlobaidi he is referring to the Strings in the table, starting [here](https://developer.aleo.org/aleo/opcodes#commitbhp256). I'm going to remove these now.

**Comment by moAlobaidi** [comment]
@aharshbe Ahh gotchu, I see them now. That sounds good!

**Comment by aharshbe** [comment]
Just created the PR. For your approval @acoglio. cc-ing @AleoHQ/tech-ops for review as well.

**Comment by aharshbe** [comment]
PR approved and merged so closing thsi.
