### ISSUE TITLE
Clarify some details of private key generation.

### ISSUE THREAD

**Issue by acoglio** [AleoHQ/welcome#196]
I suggest to improve the description of [private key generation](https://developer.aleo.org/concepts/accounts#generate-a-private-key) as follows, in order to have a precise definition of private key generation (amenable to formal specification):
- Add a link to [RFC 7693](https://www.rfc-editor.org/rfc/rfc7693) — the official definition of BLAKE.
- The official spelling is BLAKE2s, not Blake2s. (Maybe not a big deal.)
- The notation Blake2s(arg1,arg2) suggests keyed BLAKE2s, but my reading of the snarkVM code a while ago (this should be double-checked) indicates unkeyed BLAKE2s, with the two arguments suitably concatenated.
- I think it would be better to use a concatenation notation for the two parts of the input, instead of two arguments separated by commas.
- Clarify that the 0 and 1 passed as second arguments to calculate `sk_sig` and `sk_prf` are encoded as unsigned 16-bit integers, same as `counter` to calculate `r_pk`.
- I would expand `u16` to unsigned 16-bit integer.
- The endianness of the two bytes that form these `u16`s should be clarified. My reading of the snarkVM code a while ago indicates little endian (this should be double-checked).
- There is a [pending PR](https://github.com/AleoHQ/welcome/pull/93) to clarify that the counter starts at 2 to calculate `r_pk`.

**Comment by moAlobaidi** [comment]
hi @acoglio! working on this and had a question about concatenation notation: would concatenating string a and string b be written as a ∥ b? thank you in advance for the clarification.

**Comment by moAlobaidi** [comment]
Yup for sure, echoing that it's better to describe them as byte sequences, sorry about that. Think 

>  saying "<something using |>, where | denotes concatenation".

is the best option here. Will go with that for now as it makes things crystal clear to the reader.

**Comment by moAlobaidi** [comment]
[PR](https://github.com/AleoHQ/welcome/pull/200) closes this issue.
