### ISSUE TITLE
Update https://developer.aleo.org/testnet/public_endpoints/records_unspent/ with the correct usage

### ISSUE THREAD

**Issue by aharshbe** [AleoHQ/welcome#197]
The docs [here](https://developer.aleo.org/testnet/public_endpoints/records_unspent/) may be confusing. Provide the following for correct usage using snarkos:

- `snarkos developer scan --view-key "${VIEWKEY}" --endpoint "https://vm.aleo.org/api" --last 100`
- `snarkos developer scan --private-key "${PRIVATEKEY}" --endpoint "https://vm.aleo.org/api"`
- `snarkos developer scan --view-key "${VIEWKEY}" --endpoint "https://vm.aleo.org/api" --start 30000 --end 50636`

**Comment by moAlobaidi** [comment]
PR #203 closes this issue.
