### ISSUE TITLE
Add new Leo group element syntax to operators table

### ISSUE THREAD

**Issue by collinc97** [AleoHQ/welcome#198]
# Overview
New Leo syntax just dropped🔥

Operators and syntax can be found in this PR https://github.com/AleoHQ/leo/pull/2394

- [x] Add each operator to table https://developer.aleo.org/leo/operators#table-of-standard-operators
- [x] Check that arguments and return type are correct

**Comment by moAlobaidi** [comment]
Hi @collinc97! Looks like these new operators are already added and their return types and arguments are correctly reflected in the current documentation. The only thing I noticed was the documentation assign some variable a to i128 type which may make it unclear that ANY type is supported. Would you like me to add a clarification on this front?

**Comment by moAlobaidi** [comment]
Will mark this as pending close for now.

**Comment by collinc97** [comment]
closed by https://github.com/AleoHQ/welcome/pull/177
