### ISSUE TITLE
Create a "Changelog" section in the docs above Aleo

### ISSUE THREAD

**Issue by aharshbe** [AleoHQ/welcome#213]
<img width="832" alt="image" src="https://github.com/AleoHQ/welcome/assets/17191728/7663b55d-e1d1-474b-83f4-25f7eea01bb8">

Create a `Changelog` section above Aleo in the nav bar (see screenshot). We'll use this section to highlight changes and feature updates on an ongoing basis. The first addition to this changelog should be the fixes outlined in [this project](https://github.com/orgs/AleoHQ/projects/4).

**Comment by moAlobaidi** [comment]
PR #218 addresses this issue.
