### ISSUE TITLE
Right Hand Side of Shift and Exponent Operators must be 8-bit, 16-bit or 32-bit unsigned int

### ISSUE THREAD

**Issue by craigjson** [AleoHQ/welcome#276]
This is not currently documented, I checked with Pranav and he confirmed. It would be helpful to have a note in the Arithmetic operators section detailing this limitation. 

<img width="621" alt="Screenshot 2023-09-14 at 11 45 05 PM" src="https://github.com/AleoHQ/welcome/assets/16459396/f07fe31b-1112-4fe2-af0e-7241dc528918">

<img width="627" alt="Screenshot 2023-09-14 at 11 45 23 PM" src="https://github.com/AleoHQ/welcome/assets/16459396/84267a2c-0df3-4491-ab32-d51572818b95">

<img width="629" alt="image" src="https://github.com/AleoHQ/welcome/assets/16459396/0fa9764f-91d3-402e-a82b-9b6712394742">

**Comment by collinc97** [comment]
This is documented in the reference for Leo operators https://developer.aleo.org/leo/operators#shl
