### ISSUE TITLE
Hello world example need to be updated

### ISSUE THREAD

**Issue by acoglio** [AleoHQ/welcome#31]
The example at https://developer.aleo.org/developer/getting_started/syntax#syntax-to-circuits is
```
// The 'hello-world' main function.
function main(a: u32) -> u32 {
    return a
}
```
but when I run the latest version of Leo from GitHub I get
```
// The 'hello-world' main function.
function main(a: u32, b: u32) -> u32 {
    let c: u32 = a + b;
    return c
}
```
(which is indeed a nicer example to show).

**Comment by moAlobaidi** [comment]
Closing this issue as it has already been resolved. Thank you for pointing this out!
