### ISSUE TITLE
What is the precise format for block time?

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/welcome#37]
https://developer.aleo.org/aleo/concepts/blocks#timestamp
https://developer.aleo.org/autogen/testnet/public_endpoints/getblock#response

Is it seconds, milliseconds, microseconds or nanoseconds since epoch?

**Comment by aharshbe** [comment]
Hey @kellpossible the answer to this is seconds. You can find a number of references [here](https://github.com/search?q=org%3AAleoHQ+block+time+seconds&type=code). If you have any further questions feel free to reach out to our Tech Ops team via techops@aleo.org.
