### ISSUE TITLE
Aleo Studio message when no updates are available

### ISSUE THREAD

**Issue by acoglio** [AleoHQ/welcome#45]
When starting Aleo Studio, the notification shown in the attached screenshot comes up.

When I first say the '[Not Available]' starting message text, I instinctively thought there was some error (e.g. some plugin or tool not being found). The rest of the message is clear and reassuring, but I would suggest to avoid starting the notification with what looks like a "negative", i.e. '[Not Available]'. Perhaps that part could be simply deleted, leaving the rest of the message. Another option could be not to show any message at all if there are no updates available, and instead show a message if there are updates.

![image](https://user-images.githubusercontent.com/2409151/105461632-5a72c500-5c42-11eb-9e9b-76679725d2d7.png)

**Comment by aharshbe** [comment]
Closing this since Aleo Sudio is deprecated.
