### ISSUE TITLE
'aleo-studio' in Aleo Studio menu

### ISSUE THREAD

**Issue by acoglio** [AleoHQ/welcome#46]
This is purely aesthetic, but the menu on macOS references 'aleo-studio' instead of 'Aleo Studio', as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/2409151/105621481-9d58a800-5dbc-11eb-85b2-a1887eef0218.png)

**Comment by aharshbe** [comment]
Closing this since Aleo Studio is deprecated.
