### ISSUE TITLE
Leo.toml [package] vs [project]

### ISSUE THREAD

**Issue by bendyarm** [AleoHQ/welcome#77]
Two problems with the doc about `Leo.toml`.
Problem 1:
The section "File Syntax", describing `Leo.toml`, mentions the section `[package]`
but when I do `leo new hello-world` my `Leo.toml` contains `[project]`, not `[package]`.
Problem 2:
The section "File Syntax" does not describe the `[remote]` section.

**Comment by aharshbe** [comment]
Hey @bendyarm can you link to the specific doc you are referring to here? Happy to make the changes!

**Comment by bendyarm** [comment]
I think this is obsolete.
