### ISSUE TITLE
doc on .state file

### ISSUE THREAD

**Issue by bendyarm** [AleoHQ/welcome#78]
In https://developer.aleo.org/developer/getting_started/syntax#wiring-program-inputs
it mentions the `.state` file but does not describe its contents.

Is the `.state` file used for anything?  When I do `leo new hello-world`, if I want to
change the input and output data types, I can do that in the `.in` file.  At that point
the `.state` file is inconsistent with the `.in` file.  However, I don't seem to see anything
go wrong due to this inconsistency.  It is as if the `.state` file is ignored.  However,
the fact that it is inconsistent is worrisome.

**Comment by bendyarm** [comment]
I should add, if I remove the `.state` file then `leo run` gets an error like this:
```
Error: Cannot read from the provided file path - "/home/batman/minimal/compound-assignments/inputs/compound-assignments.state"
```

**Comment by aharshbe** [comment]
@bendyarm page no longer exists, okay to close?

**Comment by bendyarm** [comment]
I think this is obsolete.
