### ISSUE TITLE
doc on division should describe semantics

### ISSUE THREAD

**Issue by bendyarm** [AleoHQ/welcome#79]
https://developer.aleo.org/developer/language/operators#arithmetic-operators

Documentation on division should describe the semantics on integers.
Is `a/b` well-defined if `a` is not a multiple of `b`?
Does it do floor, or ceiling, or round?
Does it adjust towards negative infinity or towards 0?

It would probably also be good to mention that division on field values
`a/b` should be well defined for any field values `a` and `b` except `b` = `0field`.

**Comment by aharshbe** [comment]
Page no longer exists, okay to close @bendyarm?

**Comment by bendyarm** [comment]
@aharshbe  A new link would be https://developer.aleo.org/leo/operators#div
Reviewing that, it says:
```
For integer types, this operation performs truncated division. 
```
It would be good to define what that means, and to have all four examples of positive or negative divided by positive or negative.

My otherc omment about field division is still valid.

Another problem, where it says
```
...For example, div -128i8 -1i8 would result...
```
That is not Leo syntax.  It should say `-128i8 / -1i8`

**Comment by bendyarm** [comment]
I'll remove the pending close label just so it doesn't get closed by accident.

**Comment by moAlobaidi** [comment]
Hi @bendyarm! Just opened PR #207 to close this issue.

**Comment by moAlobaidi** [comment]
PR #207 closes this issue.
